# Generated by Django 4.0.5 on 2022-06-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
